/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package atividade3.uc09;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class TelaInicial extends javax.swing.JFrame {
    
    
    private final String[] tableColumns = {"Paciente", "CPF", "Telefone","Data", "Já era Paciente?", "Consulta Realizada"};
 
    DefaultTableModel tableModel = new DefaultTableModel(tableColumns, 0);
 
    private List<Consulta> consultas = new ArrayList<Consulta>();    
    
    

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        setLocationRelativeTo(null);
    }

    
    public List<Consulta> getConsultas() {
        return consultas;
    }
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPacientes = new javax.swing.JTable();
        lblTitulo = new javax.swing.JLabel();
        btnExcluirC = new javax.swing.JButton();
        btnFinalizarC = new javax.swing.JButton();
        btnNovaC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Paciente", "CPF", "Telefone", "Data", "Já era Paciente?", "Consulta Realizada"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPacientes);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setText("Boas Vindas ao Sistema de Agendamento");

        btnExcluirC.setText("Excluir Consulta");
        btnExcluirC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirCActionPerformed(evt);
            }
        });

        btnFinalizarC.setText("Finalizar Consulta");
        btnFinalizarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarCActionPerformed(evt);
            }
        });

        btnNovaC.setText("Nova Consulta");
        btnNovaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addGap(0, 214, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnNovaC, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExcluirC)
                .addGap(18, 18, 18)
                .addComponent(btnFinalizarC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovaC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFinalizarC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaCActionPerformed
        
        // Cria uma nova instância da tela de cadastro e a exibe
        TelaCadastro telaCadastro = new TelaCadastro();
        telaCadastro.setTelaInicial(this);  
        telaCadastro.setVisible(true);
  
    }//GEN-LAST:event_btnNovaCActionPerformed

    
    private void btnExcluirCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirCActionPerformed
       
        // Chama o método para excluir a consulta na posição selecionada na tabela
        try {
            
            excluirConsulta(getPosicaoConsulta());
            
        } catch (IndexOutOfBoundsException e) {
            
            JOptionPane.showMessageDialog(rootPane, "Selecione uma consulta");
            
        }
   
    }//GEN-LAST:event_btnExcluirCActionPerformed

    
    private void btnFinalizarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarCActionPerformed
 
        // Cria uma nova instância da tela de detalhes da consulta e a exibe
        try {
         
            TelaDetalhesC telaDetalhesC = new TelaDetalhesC();
            telaDetalhesC.setTelaInicial(this);
            telaDetalhesC.setConsulta(getConsulta());
            telaDetalhesC.validaConsulta();
            telaDetalhesC.setVisible(true);
            
        } catch (IndexOutOfBoundsException e) {
            
            JOptionPane.showMessageDialog(rootPane, "Selecione uma consulta");
            
        }
       
    }//GEN-LAST:event_btnFinalizarCActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
  
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new TelaInicial().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluirC;
    private javax.swing.JButton btnFinalizarC;
    private javax.swing.JButton btnNovaC;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblPacientes;
    // End of variables declaration//GEN-END:variables

    
    

    // Método para inserir uma nova consulta na lista de consultas
    public void inserirConsulta(Consulta consulta){

        consultas.add(consulta);
        
    }
    
    
    
    // Método para atualizar a tabela de consultas na tela inicial
    public void atualizarTabela(){
     
     if(!consultas.isEmpty()){
      
         Consulta consulta;
       
         tableModel = new DefaultTableModel(tableColumns, 0);
      
         for (int i = 0; i < consultas.size(); i++) {
         
             consulta = consultas.get(i);
          
             String[] rowData = {consulta.getPaciente().getNome(), consulta.getPaciente().getCpf(), consulta.getPaciente().getTelefone(),
                 consulta.getPaciente().getData(), consulta.getPaciente().getEraPaciente(), consulta.getConsultaRealizada()};
           
             tableModel.addRow(rowData);
         }
      
         tblPacientes.setModel(tableModel);
         
     }else{
       
         tableModel = new DefaultTableModel(tableColumns, 0);
         tblPacientes.setModel(tableModel);
         
     }     
  }
    
    
    
    // Método para obter a posição da consulta selecionada na tabela
      private int getPosicaoConsulta(){
    
     int posConsulta = tblPacientes.getSelectedRow();
    
     return posConsulta;
  }
      
      
      
      // Método para obter a consulta selecionada na tabela
      private Consulta getConsulta() {
          
          Consulta consulta = consultas.get(getPosicaoConsulta());
            
        return consulta;
        
      }
      
      

      
      // Método para excluir uma consulta da lista de consultas
       private void excluirConsulta(int posConsulta){
    
         if(posConsulta >= 0){
        
         
             // Exibe um diálogo de confirmação para a exclusão da consulta
            String[] options = { "Sim", "Não" };
         
            int deletar = JOptionPane.showOptionDialog(
                 rootPane,
                 "Tem certeza que deseja excluir?", 
                 "Exclusão de consulta", 
                 JOptionPane.DEFAULT_OPTION, 
                 JOptionPane.QUESTION_MESSAGE, 
                 null, 
                 options, 
                 options[0]
            );
        
            // Remove a consulta da lista e atualiza a tabela
            if(deletar == 0){
               
                 consultas.remove(posConsulta);

                 atualizarTabela();
                 
            }else{
             
                tblPacientes.clearSelection();    
            
            }
        }  
    }
    
}


